export const myProjects = [
  {
    title: "Food Order Management",
    description:
      "A responsive and interactive food ordering dashboard built with React and Tailwind CSS. This project features real-time order creation, item selection, customer input, dynamic price calculation, and order status management (total, delete, deliver).",
    image: "/food order management.png",
    link: "https://github.com/khandoker-tahmid-sami/Food-Order-Management",
    view: "https://food-order-management-nine.vercel.app/",
    features: [
      "Add New Orders",
      "Real-time Order List",
      "Filter Orders by Status",
      "Order Management",
      "Order Summary Dashboard",
      "Component-Based Architecture",
    ],
    technologies: ["React", "Vite", "JavaScript", "Tailwind CSS"],
  },
  {
    title: "Task Management App",
    description:
      "A simple and responsive task management tool built with React and Tailwind CSS. It allows users to add, edit, and prioritize tasks with tags and favorite options. Includes modal-based forms, state management, and clean UI/UX for productivity.",
    image: "/task management app.png",
    link: "https://github.com/khandoker-tahmid-sami/Task-Management-App",
    view: "https://task-management-app-orpin-eight.vercel.app/",
    features: [
      "Add New Tasks",
      "Edit Existing Tasks",
      "Delete Tasks",
      "Mark as Favorite",
      "Priority Levels",
      "Component-Based Architecture",
    ],
    technologies: ["React", "Vite", "JavaScript", "Tailwind CSS"],
  },
  {
    title: "Cine Rental Movie App",
    description:
      "A responsive and interactive movie rental dashboard built with React and Tailwind CSS. This project lets users explore a movie catalog, view details in a modal, and add movies to a cart with toast notifications. It is built using a component-based architecture and supports light/dark themes.",
    image: "/cine rental movie app.png",
    link: "https://github.com/khandoker-tahmid-sami/Cine-Rental-Movie-App",
    view: "https://cine-rental-movie-app.vercel.app/",
    features: [
      "Movie Listing with Genre, Rating & Price",
      "Movie Details Modal",
      "Rating Component",
      "Add to Cart Functionality",
      "Global Cart State using Context API + Reducers",
      "Cart Duplicate Prevention with Toastify Notifications",
      "Light & Dark Mode Support",
    ],
    technologies: ["React", "Vite", "JavaScript", "Tailwind CSS"],
  },
  {
    title: "Ecovista",
    description:
      "Ecovista is a dynamic and responsive weather dashboard application built with Next.js, Tailwind CSS, and the App Router architecture. It fetches real-time environmental data like air quality, temperature, wind speed, and current weather conditions based on the user's location or a selected city",
    image: "/ecovista.png",
    link: "https://github.com/khandoker-tahmid-sami/Ecovista",
    view: "https://ecovista-iota.vercel.app/",
    features: [
      "Real-time Weather Conditions (via OpenWeatherMap API)",
      "Auto Location Detection (via Geolocation API)",
      "Wind Speed & Direction",
      "Temperature Info with min/max details",
      "Air Quality Index & Pollution Details",
      "Location Switcher with 40+ cities",
      "Local Time & Date based on coordinates",
      "Dynamic route-based architecture with <ParallelLayout />",
    ],
    technologies: [
      "Next.js",
      "React",
      "JavaScript",
      "Tailwind CSS",
      "BigDataCloud API",
      "TimeZoneDB API",
      "OpenWeatherMap API",
    ],
  },
];
